;;; Pick best suggestion row and format for terminal.

(define-module (dictiloray format)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-13)
  #:export (pick-best-entry format-entry))

(define (alist-ref al key)
  (cond ((assoc key al) => cdr) (else #f)))

(define (string-down s)
  (string-downcase s))

(define (pick-best-entry word data)
  (and (pair? data)
       (let ((s (alist-ref data "status")))
         (and (number? s) (= s 1)))
       (let ((msg (alist-ref data "message")))
         (and (vector? msg)
              (positive? (vector-length msg))
              (let ((w (string-down (string-trim-both word))))
                (or
                  (vector-find msg
                               (lambda (item)
                                 (and (pair? item)
                                      (let ((k (alist-ref item "key")))
                                        (and (string? k)
                                             (string=? (string-down (string-trim-both k))
                                                       w))))))
                  (vector-ref msg 0)))))))

(define (vector-find vec pred)
  (let ((n (vector-length vec)))
    (let lp ((i 0))
      (cond ((>= i n) #f)
            ((pred (vector-ref vec i)) (vector-ref vec i))
            (else (lp (1+ i)))))))

(define (format-entry item)
  (unless (pair? item) (error "format-entry: bad row"))
  (let* ((lines '())
         (push (lambda (s) (set! lines (cons s lines)))))
    (cond ((alist-ref item "key")
           => (lambda (k) (when (and (string? k) (not (string-null? k))) (push k)))))
    (cond ((alist-ref item "paraphrase")
           => (lambda (p)
                (when (and (string? p)
                           (not (string-null? (string-trim-both p))))
                  (push (string-trim-both p))))))
    (let ((means (alist-ref item "means")))
      (when (vector? means)
        (let ((n (vector-length means)))
          (let lp ((i 0))
            (when (< i n)
              (let ((block (vector-ref means i)))
                (when (pair? block)
                  (let* ((part (or (alist-ref block "part") ""))
                         (ml (alist-ref block "means"))
                         (glosses (if (vector? ml)
                                      (filter (lambda (x)
                                                (and (string? x)
                                                     (not (string-null? (string-trim-both x)))))
                                              (vector->list ml))
                                      '())))
                    (unless (null? glosses)
                      (let ((joined (string-join glosses "；")))
                        (push (if (string-null? part)
                                  joined
                                  (string-append part " " joined))))))))
              (lp (1+ i)))))))
    (if (null? lines)
        "(无释义)"
        (string-join (reverse lines) "\n"))))
