;;; Minimal JSON reader/writer for iciba-style payloads (pure Scheme).
;;; Objects: alists with string keys (empty object is '()).
;;; Arrays: vectors. JSON null: unique json-null value (not '()).

(define-module (dictiloray json-minimal)
  ;; 勿引入 (ice-9 rdelim)：其 read-string 会遮蔽 R6RS 的 (read-string count port)，
  ;; 导致解析字面量 true/false/null 时把 count 当成「分隔符」而崩溃。
  #:use-module (rnrs io ports)
  #:export (json-null
            json-null?
            json-string->scm
            scm->json-string
            scm->json-pretty-string))

(define json-null (list 'json-null-marker))
(define (json-null? x) (eq? x json-null))

(define (skip-ws port)
  (let ((c (peek-char port)))
    (when (and (not (eof-object? c))
               (memv c '(#\sp #\ht #\lf #\cr)))
      (read-char port)
      (skip-ws port))))

(define (expect-char port ch)
  (skip-ws port)
  (let ((c (read-char port)))
    (unless (eqv? c ch)
      (error "json: expected char" ch c))))

(define (hex-digit? c)
  (or (char-numeric? c)
      (memv (char-downcase c) '(#\a #\b #\c #\d #\e #\f))))

(define (read-hex-4 port)
  (let lp ((i 0) (n 0))
    (if (= i 4)
        n
        (let ((c (read-char port)))
          (when (or (eof-object? c) (not (hex-digit? c)))
            (error "json: bad \\u escape"))
          (lp (1+ i)
              (+ (* n 16)
                 (cond
                  ((char-numeric? c) (- (char->integer c) (char->integer #\0)))
                  (else (+ 10 (- (char->integer (char-downcase c))
                                 (char->integer #\a)))))))))))

(define (json-codepoint->char n)
  "JSON \\u 标量：拒绝孤立代理码点，其它非法值用 U+FFFD。"
  (if (and (integer? n)
           (>= n 0)
           (<= n #x10FFFF)
           (not (and (>= n #xD800) (<= n #xDFFF))))
      (integer->char n)
      (integer->char #xfffd)))

(define (read-json-unicode-escape port)
  "读取 \\uXXXX；若为 UTF-16 高代理则再读 \\uXXXX 并合并为补充平面字符。"
  (let ((u1 (read-hex-4 port)))
    (if (and (>= u1 #xD800) (<= u1 #xDBFF))
        (let ((c0 (read-char port)))
          (if (or (eof-object? c0) (not (eqv? c0 #\\)))
              (json-codepoint->char #xfffd)
              (let ((c1 (read-char port)))
                (if (or (eof-object? c1) (not (eqv? c1 #\u)))
                    (json-codepoint->char #xfffd)
                    (let ((lo (read-hex-4 port)))
                      (if (and (>= lo #xDC00) (<= lo #xDFFF))
                          (json-codepoint->char
                           (+ #x10000 (* (- u1 #xD800) 1024) (- lo #xDC00)))
                          (json-codepoint->char #xfffd)))))))
        (json-codepoint->char u1))))

(define (read-json-string port)
  (expect-char port #\")
  (let lp ((acc '()))
    (let ((c (read-char port)))
      (cond
       ((eof-object? c) (error "json: EOF inside string"))
       ((eqv? c #\") (list->string (reverse acc)))
       ((eqv? c #\\)
        (let ((e (read-char port)))
          (cond
           ((eof-object? e) (error "json: EOF after \\"))
           ((eqv? e #\") (lp (cons #\" acc)))
           ((eqv? e #\\) (lp (cons #\\ acc)))
           ((eqv? e #\/) (lp (cons #\/ acc)))
           ((eqv? e #\b) (lp (cons (integer->char 8) acc)))
           ((eqv? e #\f) (lp (cons (integer->char 12) acc)))
           ((eqv? e #\n) (lp (cons #\lf acc)))
           ((eqv? e #\r) (lp (cons #\cr acc)))
           ((eqv? e #\t) (lp (cons #\ht acc)))
           ((eqv? e #\u)
            (lp (cons (read-json-unicode-escape port) acc)))
           (else (error "json: bad escape" e)))))
       (else (lp (cons c acc)))))))

(define (read-json-number port)
  ;; 不能用 read-delimited：它会吃掉结束用的 , } ]，而 read-json-object 还要再读分隔符。
  (skip-ws port)
  (let lp ((acc '()))
    (let ((c (peek-char port)))
      (cond
       ((eof-object? c)
        (error "json: EOF inside number"))
       ((memv c '(#\sp #\ht #\lf #\cr #\, #\} #\]))
        (if (null? acc)
            (error "json: bad number (empty)")
            (or (string->number (list->string (reverse acc)))
                (error "json: bad number" (list->string (reverse acc))))))
       (else (read-char port) (lp (cons c acc)))))))

(define (read-json-object port)
  (expect-char port #\{)
  (skip-ws port)
  (if (eqv? (peek-char port) #\})
      (begin (read-char port) '())
      (let lp ((pairs '()))
        (let ((key (read-json-string port)))
          (expect-char port #\:)
          (let ((val (read-json port)))
            (skip-ws port)
            (let ((c (read-char port)))
              (cond
               ((eqv? c #\,)
                (lp (cons (cons key val) pairs)))
               ((eqv? c #\})
                (reverse (cons (cons key val) pairs)))
               (else (error "json: in object" c)))))))))

(define (read-json-array port)
  (expect-char port #\[)
  (skip-ws port)
  (if (eqv? (peek-char port) #\])
      (begin (read-char port) #())
      (let lp ((elts (list (read-json port))))
        (skip-ws port)
        (let ((c (peek-char port)))
          (cond
           ((eqv? c #\,)
            (read-char port)
            (lp (cons (read-json port) elts)))
           ((eqv? c #\])
            (read-char port)
            (list->vector (reverse elts)))
           (else (error "json: in array" c)))))))

(define (read-json port)
  (skip-ws port)
  (let ((c (peek-char port)))
    (cond
     ((eof-object? c) (error "json: unexpected EOF"))
     ((eqv? c #\{) (read-json-object port))
     ((eqv? c #\[) (read-json-array port))
     ((eqv? c #\") (read-json-string port))
     ((eqv? c #\-) (read-json-number port))
     ((char-numeric? c) (read-json-number port))
     ((eqv? c #\t)
      (read-char port)
      (unless (equal? (get-string-n port 3) "rue")
        (error "json: true"))
      #t)
     ((eqv? c #\f)
      (read-char port)
      (unless (equal? (get-string-n port 4) "alse")
        (error "json: false"))
      #f)
     ((eqv? c #\n)
      (read-char port)
      (unless (equal? (get-string-n port 3) "ull")
        (error "json: null"))
      json-null)
     (else (error "json: bad token" c)))))

(define (json-strip-utf8-bom str)
  (if (and (> (string-length str) 0)
           (eqv? (string-ref str 0) (integer->char #xfeff)))
      (substring str 1 (string-length str))
      str))

(define (json-string->scm str)
  (read-json (open-input-string (json-strip-utf8-bom str))))

(define (write-json-string str port)
  (write-char #\" port)
  (string-for-each
   (lambda (ch)
     (let ((i (char->integer ch)))
       (cond
        ((eqv? ch #\") (display "\\\"" port))
        ((eqv? ch #\\) (display "\\\\" port))
        ((eqv? ch #\lf) (display "\\n" port))
        ((eqv? ch #\cr) (display "\\r" port))
        ((eqv? ch #\ht) (display "\\t" port))
        ((= i 8) (display "\\b" port))
        ((= i 12) (display "\\f" port))
        (else (write-char ch port)))))
   str)
  (write-char #\" port))

(define (write-json-vector x port)
  (write-char #\[ port)
  (let ((n (vector-length x)))
    (let lp ((i 0))
      (when (< i n)
        (when (> i 0) (write-char #\, port))
        (write-json (vector-ref x i) port)
        (lp (1+ i)))))
  (write-char #\] port))

(define (write-json-alist-object x port)
  (write-char #\{ port)
  (let lp ((rest x) (first? #t))
    (cond
     ((null? rest)
      (write-char #\} port))
     (else
      (unless first? (write-char #\, port))
      (let ((k (caar rest))
            (v (cdar rest)))
        (unless (string? k) (error "json: object keys must be strings" k))
        (write-json-string k port)
        (write-char #\: port)
        (write-json v port)
        (lp (cdr rest) #f))))))

(define (write-json x port)
  (cond
   ((json-null? x) (display "null" port))
   ((eq? x #t) (display "true" port))
   ((eq? x #f) (display "false" port))
   ((string? x) (write-json-string x port))
   ((number? x) (display (number->string x) port))
   ((vector? x) (write-json-vector x port))
   ((null? x) (display "{}" port))
   ((pair? x) (write-json-alist-object x port))
   (else (error "json: cannot serialize" x))))

(define (scm->json-string x)
  (call-with-output-string (lambda (p) (write-json x p))))

(define (scm->json-pretty-string x)
  (string-append (scm->json-string x) "\n"))
